## NumPy

O `NumPy` é um pacote para computação científica em `Python`. Ela dá suporte para arrays e matrizes multidimensionais, e implementa operações e funções matemáticas eficientes sobre esses conjuntos.

Na maior parte dos casos empregaremos as funções matemáticas do `NumPy`, como operações para manipulação de matrizes e vetores, funções trigonométricas, estatísticas e de randomização. O `Pandas`, pacote de manipulação de dados que empregaremos, é construído sobre o `NumPy`.

Precisamos aqui de entender apenas algumas poucas classes de `NumPy` e, assim, um pequeno conjunto de exemplos será suficiente para nossos propósitos.



### Criando arrays

Arrays podem ser de uma ou mais dimensões mas, diferentemente de listas `Python`, todos elementos devem ser do mesmo tipo. Arrays `Numpy` são indexados e seguem as mesmas regras de indexação do `Python` de listas e strings, isto é, iniciam por $0$ e o limite superior indicará o limite $<$ de range de valores a ser selecionado.

In [1]:
import numpy as np

array1D = np.array([1,2,3])
array2D = np.array([[1,2,3,4],[11,12,13,14],[21,22,23,24]])

print(array1D.ndim, array2D.ndim) # dimensões
print(array1D.shape, array2D.shape) # tamanho de cada dimensão

print(array1D)
print(array2D)

print(array1D[1])
print(array2D[1:3])
print(array2D[1][3])

1 2
(3,) (3, 4)
[1 2 3]
[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]
2
[[11 12 13 14]
 [21 22 23 24]]
14


Os arrays `NumPy` operam como listas indexadas e você pode empregar as mesmas formas de índices e iteração que empregamos em listas para percorrer arrays `NumPy`.

In [2]:
for i in range(array1D.shape[0]):
    print(i, array1D[i])

for i in range(array2D.shape[0]):       # percorre as linhas
  for j in range(array2D.shape[1]):     # percorre as colunas
    print(i, j, array2D[i,j])

for elem in array1D:
    print(elem)

for linha in array2D:                   # percorre as linhas
  for coluna in linha:                  # percorre as colunas
    print(coluna)

0 1
1 2
2 3
0 0 1
0 1 2
0 2 3
0 3 4
1 0 11
1 1 12
1 2 13
1 3 14
2 0 21
2 1 22
2 2 23
2 3 24
1
2
3
1
2
3
4
11
12
13
14
21
22
23
24


### Operações sobre arrays `NumPy`

Um dos recursos mais úteis do `NumPy`, e que não encontramos em linguagens como Java e C, é que diversas  operações podem ser executadas diretamente sobre toda a coleção de dados sem a necessidade de iterações ou laços de programa.

In [3]:
x = np.array([1,2,3])
print( np.mean(x), np.sum(x), np.power(x,2) )
print( 2*x, x+x, x**2 + 2*x + 1, np.log(x) )

2.0 6 [1 4 9]
[2 4 6] [2 4 6] [ 4  9 16] [0.         0.69314718 1.09861229]


### Outras Operações Úteis

Ainda, algumas operações de conversão, randomização e criação de sequencias de valores são muito úteis e serão empregadas ao longo de todo o livro.

In [4]:
x = np.array([1,2,3])

x_list = x.tolist()  # convertendo um NumPy array para uma lista `Python`
print(x, x_list)

np.random.seed(1984)                                    # semente de geração aleatória
print( np.random.randint(low=1, high=6, size=10) )      # gerando inteiros aleatórios
print( np.random.rand(4) )                              # gerando valores aleatórios entre [0,1]
print( np.random.sample(5) )                            # gerando um sample de dados aleatórios

print( np.arange( 10, 20, 2) )     # gerando uma lista de valores no intervalo [10,20[ com incrementos de 2

print( np.linspace( 10, 20, 50) )  # gerando uma lista de valores de 50 valores no intervalo [10,20[


[1 2 3] [1, 2, 3]
[5 4 2 1 1 3 3 2 3 1]
[0.99873856 0.89441845 0.26139183 0.73330439]
[0.14629798 0.17234917 0.61481704 0.59564882 0.68232631]
[10 12 14 16 18]
[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


#### NumPy functions

As funções básicas estão disponíveis nativamente, mas para muitas funções matemáticas como funções trigonométricas, randomização e constantes como o $\pi$ e $e$ é necessário recorrer a bibliotecas numéricas como o `NumPy` ou  `math` e, em geral, empregaremos o `NumPy`.



In [5]:
import numpy as np

print(np.pi)            # pi
print(np.exp(1))        # e

print(5 % 2)
# o mesmo que
print(np.mod(5,2))

print(np.random.rand(1))
print(np.random.sample(10))

3.141592653589793
2.718281828459045
1
1
[0.6222255]
[0.27434577 0.94900978 0.0711977  0.76115161 0.77789187 0.19048369
 0.18946263 0.39458303 0.35415793 0.0463781 ]


### Operações com matrizes

Exemplo:
Dadas as matrizes A=[1 0 3; 5 4 1; 2 3 1] e B=[3 1 4; 1 2 1; 3 1 1],

determinar:

A+B          % soma de matrizes

A*B           % multiplicação de matrizes

det(A)       % determinante da matriz A

B'              % transposta da matriz B

2*B           % multiplicação de um número real pela matriz B

inv(A)        % matriz inversa de A

eye(3)       % matriz identidade de 3 linhas e 3 colunas

zeros(3,2) % matriz de 3 linhas e duas colunas com valores zeros


In [6]:
import numpy as np
A=np.array([[1,0,3],[5,4,1],[2,3,1]])
print('A=\n',A)
B=np.array([[3,1,4],[1,2,1],[3,1,1]])
print('B=\n',B)

A=
 [[1 0 3]
 [5 4 1]
 [2 3 1]]
B=
 [[3 1 4]
 [1 2 1]
 [3 1 1]]


In [7]:
C=A+B
print('C=\n',C)

C=
 [[4 1 7]
 [6 6 2]
 [5 4 2]]


In [8]:
D=np.dot(A,B)
print('D=\n',D)

D=
 [[12  4  7]
 [22 14 25]
 [12  9 12]]


In [9]:
det=np.linalg.det(A)
print('%.2f'% det)

22.00


In [10]:
print('\nObtendo a transposta')
a_transposta = B.T
print(a_transposta)
print(a_transposta.shape)


Obtendo a transposta
[[3 1 3]
 [1 2 1]
 [4 1 1]]
(3, 3)


In [11]:
E=2*B
print('E=\n',E)

E=
 [[6 2 8]
 [2 4 2]
 [6 2 2]]


In [12]:
inv=np.linalg.inv(A)
print(inv)

[[ 0.04545455  0.40909091 -0.54545455]
 [-0.13636364 -0.22727273  0.63636364]
 [ 0.31818182 -0.13636364  0.18181818]]


In [13]:
F=np.identity(3)
print('F=\n',F)

F=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
G=np.zeros((3,2))
print('G=\n',G)

G=
 [[0. 0.]
 [0. 0.]
 [0. 0.]]



## Pandas

O `Pandas` é um pacote `Python` construído sobre `Numpy` para manipulação e análise de dados orientado a colunas. Ele organiza os dados em dois tipos de estruturas, `Series` e `DataFrames`, e opera seleções e transformações sobre essas coleções.

* **`DataFrame`**: você pode entender um `DataFrame` como uma tabela de dados relacionais, com linhas e colunas nomeadas, como você encontra em Excel ou na SQL.

* **`Series`**: é uma única coluna de dados somente com os seus valores, e o `DataFrame` contém um ou mais `Series` com um nome para cada uma delas.

O `DataFrame`, implementado em `Python`, é uma abstração comumente usada para manipulação de dados que tem origem na linguagem R, mas você encontrará implementações similares também em outras linguagens.


### Import da biblioteca

In [15]:
import pandas as pd
import numpy as np

### Criando um `pd.Series` e um `pd.DataFrame`

Uma `pd.Series` pode ser criada a partir de uma lista e um `pd.Dataframe` pode ser criado empregando-se uma estrutura de dicionário.

In [16]:
# Séries
student_names = pd.Series(['Adriana', 'Carol', 'Daniel'])
age = pd.Series([18, 19, 19])

# DataFrame
students = pd.DataFrame({ 'Student Name': student_names, 'Age': age })
students


Student Name  Age
0      Adriana   18
1        Carol   19
2       Daniel   19

### Lendo um `DataFrame`

O uso mais comum do `Pandas` que faremos é para o acesso a arquivos e bases de dados e o `Pandas` permite ler e gravar dados de diferentes fontes como arquivos `.csv, .json, .xlsx` e bancos de dados `sql`, Mongo etc.


| Format        | Read           | Save          |
| ------------- |:--------------:| ----------------:|
| csv           | `pd.read_csv()`  |`df.to_csv()`     |
| json          | `pd.read_json()` |`df.to_json()`    |
| xlsx          | `pd.read_excel()`|`df.to_excel()`   |
| hdf           | `pd.read_hdf()`  |`df.to_hdf()`     |
| sql           | `pd.read_sql()`  |`df.to_sql()`     |

acessados local ou pela internet.


In [36]:
tips = pd.read_csv('https://raw.githubusercontent.com/Rogerio-mack/Visualizacao-de-Dados-em-Python/main/data/tips.csv')
tips.head()


total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
..         ...   ...     ...    ...  ...     ...   ...
95       40.17  4.73    Male    Yes  Fri  Dinner     4
96       27.28  4.00    Male    Yes  Fri  Dinner     2
97       12.03  1.50    Male    Yes  Fri  Dinner     2
98       21.01  3.00    Male    Yes  Fri  Dinner     2
99       12.46  1.50    Male     No  Fri  Dinner     2

[100 rows x 7 columns]

Acima, o comando `df.head()` exibe o aspecto inicial dos dados a partir de suas primeiras linhas.

### Explorando a estrutura básica dos dados

Antes de explorarmos o conteúdo dos dados é útil acessar informações sobre a estrutura dos dados que estamos lidando, como os valores que assumem os dados, quantas linhas temos em uma tabela, o número de atributos e os tipos dos dados.

In [18]:
tips.shape # nr de linhas e colunas

(244, 7)

In [19]:
len(tips) # número de linhas

244

In [20]:
tips.columns.to_list() # ou tips.columns

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

In [21]:
tips.dtypes # tipo dos atributos

total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

O comando `describe()` exibe informações estatísticas sumarizadas dos dados.

In [22]:
tips.describe(include='all')

total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

### Selecionando Dados

Seleções dos dados são bastante importantes. Você nem sempre estará interessado em exibir ou analisar todos os dados. Por exemplo, você pode ter dados de produção de várias unidades de uma fábrica, mas estar interessado somente em dados das unidades de São Paulo (seleção de linhas ou casos). Ou, você pode ter dados de vendas com diversas informações dos produtos (cor, modelo etc.) e dos clientes (nome, CPF etc.) e quer apenas dados de peso e dimensões do produto, da origem e destino da compra, para analisar os preços de frete (seleção de colunas ou atributos). E mais frequentemente ainda você vai realizar as duas seleções criando *slices* (fatias) dos dados com as informações de interesse.



### Seleção de Colunas, Seleção de Linhas e de Linhas e Colunas

<img src="https://pandas.pydata.org/docs/_images/03_subset_columns.svg" width=320, align="center">
<img src="https://pandas.pydata.org/docs/_images/03_subset_rows.svg" width=320, align="center">
<img src="https://pandas.pydata.org/docs/_images/03_subset_columns_rows.svg" width=320, align="center">



### Selecionando colunas de dados como `pd.Series`

As colunas de um `DataFrame` são séries do `Pandas` e podemos selecionar e operar com cada uma das séries de um `DataFrame`. Existem dois modos de seleção

```
df.<nome do atributo>

df['<nome do atributo>']
```

elas retornam o mesmo resultado e a segunda forma é sempre necessária quando temos nomes de atributos com espaços ou caracteres especiais.


In [23]:
print(tips.tip)
# ou
# print(tips['tip'])

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64


Esse conjunto de dados é um `pd.Series` e podemos fazer uma série de operações sobre essa coleção de dados, como calcular a soma ou a média de valores, como em um array `NumPy`.

In [24]:
tip_series = tips['tip']
print(f'Média das gorjetas: USD {tip_series.mean() :.2f} e Total das gorjetas: USD {tip_series.sum() :.2f}')

Média das gorjetas: USD 3.00 e Total das gorjetas: USD 731.58


Pode ser útil também você transformar uma `pd.Series` em uma lista `Python` para que você possa realizar operações de listas que você já conhece.

In [25]:
dias = tips.day
dias = dias.to_list()
dias.count('Sat')

87

### Selecionando uma ou Mais Colunas como `pd.DataFrame`

<img src="https://pandas.pydata.org/docs/_images/03_subset_columns.svg" width=320, align="center">

Você pode estar também interessado na seleção de *mais que uma coluna* de dados. Para isso você pode simplesmente informar para o `Pandas` uma **lista de atributos** a serem selecionados.

```

df [ [ <lista-de-colunas> ] ]

```

Diferente da seleção anterior que retorna um Série do `Pandas`, a seleção neste formato, com uma ou mais colunas informadas em uma lista, retornará sempre um `DataFrame`, mesmo que você informe uma única coluna.



A seleção como `DataFrame` permite a seleção de várias séries de dados (atributos) para construírmos subconjuntos dos dados. Essas seleções de dados retornam `DataFrames` e todas as operações sobre `DataFrames` são aplicáveis sobre essas seleções.

In [26]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [27]:
selected_tips = tips[['total_bill', 'tip', 'size']]

selected_tips.head() # um novo dataframe com atributos selecionados

total_bill   tip  size
0       16.99  1.01     2
1       10.34  1.66     3
2       21.01  3.50     3
3       23.68  3.31     2
4       24.59  3.61     4

$\rightarrow$ *A seleção com uma ou mais colunas informadas em uma lista, retorna um `DataFrame`. Note que `df['tip']` retorna um `pd.Series`, enquanto, selecionar `df[['tip']]` retorna um `pd.DataFrame` de uma única coluna.*



De modo geral, você pode empreguar a seleção de `pd.Series` se quiser selecionar um único atributo, e empregar a seleção `pd.DataFrame` quando estiver interessado na criação de subconjuntos de dados.

### Selecionando Maiores e Menores

Veremos mais adiante como fazer seleção de linhas, mas aqui já é oportuno vermos como selecionar linhas que contenham os maiores e os menores valores da coleção.

In [28]:
tips.nsmallest(5,'total_bill')

total_bill   tip     sex smoker   day    time  size
67         3.07  1.00  Female    Yes   Sat  Dinner     1
92         5.75  1.00  Female    Yes   Fri  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
172        7.25  5.15    Male    Yes   Sun  Dinner     2
149        7.51  2.00    Male     No  Thur   Lunch     2

In [29]:
tips_top3 = tips.nlargest(3,'total_bill')
tips_top3

total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
59        48.27   6.73  Male     No  Sat  Dinner     4

### Alterando e Incluindo Colunas de Dados

Muitas vezes é necessário você criar atributos derivados a partir dos dados originais, como converter valores para R\$ , criar um atributo com o valor das contas descontando a gorjeta ou o valor da conta dividido pelos participantes da mesa. A exemplo do `NumPy`, essa é uma grande facilidade do `Pandas` que, sendo orientado a colunas,  permite realizar operações sobre uma coluna de dados (ou mesmo toda a coleção) sem a necessidade de iterações ou laços de programa.

In [30]:
dolar_real_rate = 5.8
tips['total_bill'] = tips['total_bill'] * dolar_real_rate         # alterando
tips['tip'] = tips['tip'] * dolar_real_rate                       # alterando

tips['total_bill_minus_tips'] = tips['total_bill'] - tips['tip']    # incluindo um novo atributo
tips['bill_by_head'] = tips['total_bill'] / tips['size']            # incluindo um novo atributo
tips.head()

total_bill     tip     sex smoker  day    time  size  \
0      98.542   5.858  Female     No  Sun  Dinner     2   
1      59.972   9.628    Male     No  Sun  Dinner     3   
2     121.858  20.300    Male     No  Sun  Dinner     3   
3     137.344  19.198    Male     No  Sun  Dinner     2   
4     142.622  20.938  Female     No  Sun  Dinner     4   

   total_bill_minus_tips  bill_by_head  
0                 92.684     49.271000  
1                 50.344     19.990667  
2                101.558     40.619333  
3                118.146     68.672000  
4                121.684     35.655500

### Selecionar Linhas

<img src="https://pandas.pydata.org/docs/_images/03_subset_rows.svg" width=320, align="center">

A seleção de linhas é mais interessante por que podemos especificar condições para os valores que buscamos. Por exemplo, você pode selecionar o tipo de peças que deseja ver em um `DataFrame` com dados de vários componentes, ou selecionar as unidades de fábrica de uma certa cidade que você deseja verificar a produção.

A seleção é um predicado lógico,  

```
df [ <critério de seleção> ]
```

Exemplos

```
df [ nome_coluna == valor ]
df [ nome_coluna != valor ]
df [ nome_coluna > valor ]
```

Podemos, assim, selecionar os dados somente de não fumantes ou fumantes:

In [31]:
tips_nao_fumantes = tips[ tips.smoker == 'No' ]
tips_fumantes = tips[ tips.smoker == 'Yes' ]

### Seleção de Linhas e Colunas

<img src="https://pandas.pydata.org/docs/_images/03_subset_columns_rows.svg" width=320, align="center">

O uso mais geral das seleções é o de seleções conjuntas de linhas e colunas de dados, e nos referimos a esse subconjunto dos dados de *slice* (fatia) dos dados.

Seguindo uma boa prática sempre faremos primeiro a seleção das linhas,

```
df [ <critério de seleção> ] ...

...Selecionando uma coluna
df [ <critério de seleção> ].nome_coluna                  pd.Series
df [ <critério de seleção> ]['nome_coluna']

...Selecionando uma ou mais colunas
df [ <critério de seleção> ][ [<lista-de-colunas>] ]      pd.DataFrame

```


Com isso podemos fazer inúmeras seleções de dados que temos interesse em visualizar ou analisar, e responder a muitas perguntas sobre os dados.

- **Qual a proporção de Clientes Fumantes?**

In [32]:
print(f'Percentual de Clientes Fumantes {len( tips_fumantes ) / len( tips ) :.2f} %')

Percentual de Clientes Fumantes 0.38 %


- **Fumantes ou Mulheres, pagam mais gorjeta (em média) ?**

In [33]:
tips[ tips.smoker == 'Yes' ]['tip'].mean() > tips[ tips.smoker == 'No' ]['tip'].mean()

True

In [34]:
tips[ tips.sex == 'Female' ]['tip'].mean() > tips[ tips.sex == 'Male' ]['tip'].mean()

False

As selecões e criação desses subconjuntos de dados, como você poderá ver, têm um papel muito importante na construção de visualizações e entendimento dos dados pois, em muitos casos, recorremos a esses subconjuntos para produzir as visualizações, como no exemplo abaixo, em que observamos os valores das gorjetas de homens e mulheres.

In [38]:
import matplotlib.pyplot as plt
plt.hist(tips[ tips.sex == 'Male' ]['tip'], label='Homens')
plt.hist(tips[ tips.sex == 'Female' ]['tip'], label='Mulheres')

plt.xlabel('Valor das Gorjetas')
plt.ylabel('Quantidades Pagas')
plt.title('Distribuição das Gorjetas', fontsize=14, weight='bold')
plt.legend(title='$\\bf{Gorjetas}$')
plt.show()

ImportError: DLL load failed while importing _multiarray_umath: Não foi possível encontrar o módulo especificado.

ImportError: initialization failed

O `Pandas` ainda conta com uma série de operações para manipulação e transformação dos dados como funções de joins e merge de tabelas, groupby etc. empregaremos eventualmente essas operações ao longo do texto e para maiores detalhes você poderá consultar a documentação do `Pandas` ou outras referências online.